version: '3.3'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb
    network_mode: lambda-local
    ports:
      - "8000:8000"
    volumes:
      - "./data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

