service: web-mentions

frameworkVersion: ">=2.0.0 <4.0.0"

plugins:
  - serverless-esbuild
  - serverless-dynamodb-local
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: linked
    watch:
      pattern: 'src/**/*.ts'
  dynamodb:
    stages:
      - dev
    start:
      seed: true
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs14.x
  profile: ${param:profile} # force the profile parameter to be required
  region: ${opt:region}
  stage: ${opt:stage}
  environment:
    STATUS_TABLE: status-table-${param:profile}-${opt:stage}
    MENTION_TABLE: mention-table-${param:profile}-${opt:stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
          Resource:
            - !Sub ${statusTable.Arn}
            - !Sub ${statusTable.Arn}/index/*
            - !Sub ${mentionTable.Arn}
            - !Sub ${mentionTable.Arn}/index/*

resources:
  - ${file(./src/serverless-resources.yml)}

functions:
  - ${file(./src/serverless-functions.yml)}
