Resources:
  statusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: status-table-${param:profile}-${opt:stage}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  mentionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mention-table-${param:profile}-${opt:stage}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: target
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: target-index
          KeySchema:
            - AttributeName: target
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
